version: '3.8'

services:
  batik-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./labels.txt:/app/labels.txt
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 